### ISSUE TITLE
Install guide needed

### ISSUE THREAD

**Issue by ghost** [Brobb954/simple_budget#1]
Hey, 

I want to run your program on my machine, please add a how-to section for getting your app set up to run locally

Thanks!

**Comment by Brobb954** [comment]
Thank you for reaching out!

I will have one written up soon and provided in the readme

Thanks,
Brandon

**Comment by Brobb954** [comment]
Good Morning! An initial revision of the install guide has been published to the readme! Please feel free to reach out with any more questions or concerns!

Thanks,
Brandon
